name: Loan Prediction

channels:
  - defaults

dependencies:
  - python=3.11.4
  - pip
  - conda:
    - mlflow
    - numpy==1.25.2
    - pandas==2.0.3
    - matplotlib==3.7.1
    - scikit-learn==1.2.2